// Generated by scripts/generate-annotation-types.py. Do not edit.

export interface AnnotationConflictDetail {
  code: "annotation_conflict";
  conflicting_annotation_id: string;
}

export interface Point {
  x: number;
  y: number;
}

export interface RegisterClip {
  operation_id: string;
  source_job_id: string;
}

export interface RoiWrite {
  operation_id: string;
  expected_clip_revision: number;
  camera_setup_id: string;
  polygon: Array<Point>;
  template_revision_id?: string | null;
}

export interface MediaView {
  frame_count: number;
  fps_num: number;
  fps_den: number;
  width: number;
  height: number;
  sample_aspect_ratio: string;
}

export interface RoiView {
  id: string;
  revision: number;
  camera_setup_id: string;
  polygon: Array<Point>;
  template_revision_id: string | null;
}

export interface ClipView {
  schema_version?: 1;
  id: string;
  source_job_id: string;
  original_name: string;
  revision: number;
  preparation_state: "preparing" | "ready" | "failed" | "releasing" | "released";
  source_state: "available" | "missing" | "hash_mismatch";
  failure_code: string | null;
  source_sha256: string | null;
  media: MediaView | null;
  roi: RoiView | null;
  preview_url: string | null;
  prepared_bytes: number | null;
}

export interface CameraSetupCreate {
  operation_id: string;
  name: string;
}

export interface CameraSetupView {
  id: string;
  name: string;
  revision: number;
  template: RoiView | null;
}

export interface TemplateWrite {
  operation_id: string;
  expected_setup_revision: number;
  polygon: Array<Point>;
}

export interface RetryPreparation {
  operation_id: string;
  expected_clip_revision: number;
}

export interface ReleasePreparedMedia {
  operation_id: string;
  expected_clip_revision: number;
}

export interface StorageView {
  used_bytes: number;
  limit_bytes: number;
  free_bytes: number;
}

export interface ErrorView {
  detail: string | AnnotationConflictDetail;
}

export interface ClipListView {
  items: Array<ClipView>;
  next_cursor: string | null;
}

export interface CameraSetupListView {
  items: Array<CameraSetupView>;
  next_cursor: string | null;
}

export interface InteractionCreate {
  operation_id: string;
  expected_clip_revision: number;
  hand: "left" | "right" | "unknown";
  tracking_job_id?: string | null;
  local_track_id?: number | null;
}

export interface InteractionUpdate {
  operation_id: string;
  expected_clip_revision: number;
  hand: "left" | "right" | "unknown";
  tracking_job_id?: string | null;
  local_track_id?: number | null;
  expected_interaction_revision: number;
}

export interface InteractionView {
  id: string;
  clip_id: string;
  revision: number;
  hand: "left" | "right" | "unknown";
  tracking_job_id: string | null;
  local_track_id: number | null;
}

export interface ActionAnnotationCreate {
  interaction_id: string | null;
  label: "hand_in" | "hand_out" | "take_out" | "put_in" | "unclear";
  start_frame: number;
  end_frame: number;
  crossing_frame?: number | null;
  object_kind: "cash" | "other" | "unknown";
  visibility: "clear" | "occluded";
  uncertain_labels?: Array<"hand_in" | "hand_out" | "take_out" | "put_in">;
  unclear_reason?: "occlusion" | "boundary_ambiguous" | "clip_boundary" | "actor_ambiguous" | "object_ambiguous" | null;
  operation_id: string;
  expected_clip_revision: number;
  suggestion_id?: string | null;
}

export interface ActionAnnotationUpdate {
  interaction_id: string | null;
  label: "hand_in" | "hand_out" | "take_out" | "put_in" | "unclear";
  start_frame: number;
  end_frame: number;
  crossing_frame?: number | null;
  object_kind: "cash" | "other" | "unknown";
  visibility: "clear" | "occluded";
  uncertain_labels?: Array<"hand_in" | "hand_out" | "take_out" | "put_in">;
  unclear_reason?: "occlusion" | "boundary_ambiguous" | "clip_boundary" | "actor_ambiguous" | "object_ambiguous" | null;
  operation_id: string;
  expected_clip_revision: number;
  expected_annotation_revision: number;
}

export interface ActionMutation {
  operation_id: string;
  expected_clip_revision: number;
  expected_annotation_revision: number;
}

export interface ActionAnnotationView {
  interaction_id: string | null;
  label: "hand_in" | "hand_out" | "take_out" | "put_in" | "unclear";
  start_frame: number;
  end_frame: number;
  crossing_frame?: number | null;
  object_kind: "cash" | "other" | "unknown";
  visibility: "clear" | "occluded";
  uncertain_labels?: Array<"hand_in" | "hand_out" | "take_out" | "put_in">;
  unclear_reason?: "occlusion" | "boundary_ambiguous" | "clip_boundary" | "actor_ambiguous" | "object_ambiguous" | null;
  id: string;
  clip_id: string;
  roi_revision_id: string;
  revision: number;
  review_state: "draft" | "confirmed" | "needs_review";
  guideline_version?: 1;
  deleted: boolean;
}

export interface ReviewCoverageWrite {
  operation_id: string;
  expected_clip_revision: number;
  start_frame: number;
  end_frame: number;
  reviewed_labels: Array<"hand_in" | "hand_out" | "take_out" | "put_in">;
}

export interface ReviewCoverageView {
  id: string;
  clip_id: string;
  roi_revision_id: string;
  revision: number;
  start_frame: number;
  end_frame: number;
  reviewed_labels: Array<"hand_in" | "hand_out" | "take_out" | "put_in">;
  guideline_version?: 1;
  active: boolean;
}

export interface ActionWorkspaceView {
  clip_id: string;
  clip_revision: number;
  roi_revision_id: string;
  interactions: Array<InteractionView>;
  annotations: Array<ActionAnnotationView>;
  review_coverage: Array<ReviewCoverageView>;
}

export interface AssistanceRunCreate {
  operation_id: string;
  expected_clip_revision: number;
  model: "dino" | "mediapipe";
  start_frame: number;
  end_frame: number;
}

export interface AssistanceRunView {
  id: string;
  clip_id: string;
  model: "dino" | "mediapipe";
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  start_frame: number;
  end_frame: number;
  processed_frames: number;
  scheduled_frames: number;
  error_code: string | null;
  source_sha256: string;
  roi_revision_id: string;
  guideline_version?: 1;
  device: "cpu" | "cuda:0";
  config_sha256: string | null;
  asset_sha256: string | null;
  created_at: string;
  updated_at: string;
}

export interface AssistanceRunListView {
  items: Array<AssistanceRunView>;
  next_cursor: string | null;
}

export interface AssistanceSuggestionView {
  id: string;
  run_id: string;
  clip_id: string;
  proposal_key: string;
  label: "hand_in" | "hand_out" | null;
  action_start_frame?: number | null;
  action_end_frame?: number | null;
  view_start_frame: number;
  view_end_frame: number;
  crossing_estimate?: number | null;
  crossing_bracket_start?: number | null;
  crossing_bracket_end?: number | null;
  reason: "crossing" | "boundary" | "track_gap" | "association" | "clip_boundary";
  review_state: "pending" | "accepted" | "rejected" | "stale";
  accepted_annotation_id: string | null;
}

export interface AssistanceSuggestionListView {
  items: Array<AssistanceSuggestionView>;
  next_cursor: string | null;
}

export interface AssistanceModelInfo {
  model: "dino" | "mediapipe";
  available: boolean;
  device: "cpu" | "cuda:0";
  error_code: string | null;
}

export interface AssistanceRunCancel {
  operation_id: string;
}

export interface SuggestionReject {
  operation_id: string;
  expected_clip_revision: number;
}
