// Generated by scripts/generate-annotation-types.py. Do not edit.

export interface Point {
  x: number;
  y: number;
}

export interface RegisterClip {
  operation_id: string;
  source_job_id: string;
}

export interface RoiWrite {
  operation_id: string;
  expected_clip_revision: number;
  camera_setup_id: string;
  polygon: Array<Point>;
  template_revision_id?: string | null;
}

export interface MediaView {
  frame_count: number;
  fps_num: number;
  fps_den: number;
  width: number;
  height: number;
  sample_aspect_ratio: string;
}

export interface RoiView {
  id: string;
  revision: number;
  camera_setup_id: string;
  polygon: Array<Point>;
  template_revision_id: string | null;
}

export interface ClipView {
  schema_version?: 1;
  id: string;
  source_job_id: string;
  original_name: string;
  revision: number;
  preparation_state: "preparing" | "ready" | "failed" | "releasing" | "released";
  source_state: "available" | "missing" | "hash_mismatch";
  failure_code: string | null;
  source_sha256: string | null;
  media: MediaView | null;
  roi: RoiView | null;
  preview_url: string | null;
  prepared_bytes: number | null;
}

export interface CameraSetupCreate {
  operation_id: string;
  name: string;
}

export interface CameraSetupView {
  id: string;
  name: string;
  revision: number;
  template: RoiView | null;
}

export interface TemplateWrite {
  operation_id: string;
  expected_setup_revision: number;
  polygon: Array<Point>;
}

export interface RetryPreparation {
  operation_id: string;
  expected_clip_revision: number;
}

export interface ReleasePreparedMedia {
  operation_id: string;
  expected_clip_revision: number;
}

export interface StorageView {
  used_bytes: number;
  limit_bytes: number;
  free_bytes: number;
}

export interface ErrorView {
  detail: string;
}

export interface ClipListView {
  items: Array<ClipView>;
  next_cursor: string | null;
}

export interface CameraSetupListView {
  items: Array<CameraSetupView>;
  next_cursor: string | null;
}
