import { useEffect, useState } from "react";
import { CaseDetail } from "./CaseDetail";
import { CaseList } from "./CaseList";
import { ReviewCase } from "./api";
import { LiveCamera, OverlayDetection } from "./LiveCamera";
export default function App() {
  const [selected, setSelected] = useState<ReviewCase>(); const [live, setLive] = useState<Record<string, string>>({ "cam-a": "checking", "cam-b": "checking" }); const [inference, setInference] = useState({ state: "checking", people_count: 0, candidates: {} as Record<string, number>, event_kinds: [] as string[], transaction_statuses: [] as string[], detections: [] as OverlayDetection[], scope: "candidate_detection_only" });
  useEffect(() => { const update = () => fetch("/api/live/status").then(r => r.json()).then(setLive).catch(() => setLive({ "cam-a": "api_unavailable", "cam-b": "api_unavailable" })); update(); const id = window.setInterval(update, 3000); return () => clearInterval(id); }, []);
  useEffect(() => { const update = () => fetch("/api/inference/status").then(r => r.json()).then(value => setInference(value["cam-a"])).catch(() => setInference({ state: "api_unavailable", people_count: 0, candidates: {}, event_kinds: [], transaction_statuses: [], detections: [], scope: "candidate_detection_only" })); update(); const id = window.setInterval(update, 1000); return () => clearInterval(id); }, []);
  return <main><header><h1>Giám sát giao dịch</h1><p>Quan sát video thuần túy; không kết luận hành vi của bất kỳ ai.</p></header><section><h2>Camera trực tiếp</h2><div><LiveCamera cameraId="cam-a" status={live["cam-a"]} detections={inference.detections} /><LiveCamera cameraId="cam-b" status={live["cam-b"]} /></div><p><strong>Model gợi ý:</strong> {inference.state === "running" ? Object.entries(inference.candidates).map(([label, count]) => `${label}: ${count}`).join(" · ") : inference.state}.</p><p><strong>Chuỗi video:</strong> {inference.event_kinds.length ? inference.event_kinds.join(" → ") : "đang chờ đủ quan sát"}.</p><small>Các nhãn tiền/rổ/hàng là gợi ý; một camera duy nhất không thể tạo cảnh báo giao dịch.</small></section>{selected ? <CaseDetail item={selected} onDone={() => setSelected(undefined)} /> : <CaseList onSelect={setSelected} />}</main>;
}
