from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from app.annotation.contracts import (  # noqa: E402
    CameraSetupCreate,
    CameraSetupListView,
    CameraSetupView,
    ClipListView,
    ClipView,
    ErrorView,
    MediaView,
    Point,
    RegisterClip,
    ReleasePreparedMedia,
    RetryPreparation,
    RoiView,
    RoiWrite,
    StorageView,
    TemplateWrite,
)


MODELS = [
    Point,
    RegisterClip,
    RoiWrite,
    MediaView,
    RoiView,
    ClipView,
    CameraSetupCreate,
    CameraSetupView,
    TemplateWrite,
    RetryPreparation,
    ReleasePreparedMedia,
    StorageView,
    ErrorView,
    ClipListView,
    CameraSetupListView,
]
SCHEMA_PATH = ROOT / "frontend" / "src" / "annotation" / "schema.generated.json"
TYPES_PATH = ROOT / "frontend" / "src" / "annotation" / "types.generated.ts"


def combined_schema() -> dict[str, Any]:
    definitions: dict[str, Any] = {}
    for model in MODELS:
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        nested = schema.pop("$defs", {})
        for name, definition in nested.items():
            if name in definitions and definitions[name] != definition:
                raise ValueError(f"conflicting JSON schema definition: {name}")
            definitions[name] = definition
        definitions[model.__name__] = schema
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "schema_version": 1,
        "models": {model.__name__: {"$ref": f"#/$defs/{model.__name__}"} for model in MODELS},
        "$defs": definitions,
    }


def schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        prefix = "#/$defs/"
        reference = schema["$ref"]
        if not isinstance(reference, str) or not reference.startswith(prefix):
            raise ValueError("unsupported JSON schema reference")
        return reference[len(prefix) :]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        if not isinstance(schema["enum"], list) or not schema["enum"]:
            raise ValueError("unsupported empty JSON schema enum")
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    if "anyOf" in schema:
        choices = schema["anyOf"]
        if not isinstance(choices, list) or not choices:
            raise ValueError("unsupported JSON schema anyOf")
        return " | ".join(schema_type(choice) for choice in choices)
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array" and isinstance(schema.get("items"), dict):
        item_type = schema_type(schema["items"])
        return f"Array<{item_type}>"
    if kind == "object" and isinstance(schema.get("properties"), dict):
        required = set(schema.get("required", []))
        fields = []
        for name, field in schema["properties"].items():
            optional = "" if name in required else "?"
            fields.append(f"{name}{optional}: {schema_type(field)}")
        return "{ " + "; ".join(fields) + " }"
    raise ValueError(f"unsupported JSON schema construct: {json.dumps(schema, sort_keys=True)}")


def _interface(name: str, schema: dict[str, Any]) -> str:
    if schema.get("type") != "object" or not isinstance(schema.get("properties"), dict):
        return f"export type {name} = {schema_type(schema)};"
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for field_name, field_schema in schema["properties"].items():
        optional = "" if field_name in required else "?"
        lines.append(f"  {field_name}{optional}: {schema_type(field_schema)};")
    lines.append("}")
    return "\n".join(lines)


def generated_outputs() -> tuple[str, str]:
    schema = combined_schema()
    schema_text = json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    definitions = schema["$defs"]
    type_blocks = [_interface(model.__name__, definitions[model.__name__]) for model in MODELS]
    types_text = (
        "// Generated by scripts/generate-annotation-types.py. Do not edit.\n\n"
        + "\n\n".join(type_blocks)
        + "\n"
    )
    return schema_text, types_text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema_text, types_text = generated_outputs()
    outputs = ((SCHEMA_PATH, schema_text), (TYPES_PATH, types_text))
    if args.check:
        stale = [path for path, expected in outputs if not path.is_file() or path.read_text("utf-8") != expected]
        if stale:
            print("Generated annotation contracts are stale: " + ", ".join(str(path) for path in stale), file=sys.stderr)
            return 1
        return 0
    for path, content in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
